[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.80", features = ["backtrace"] }
async-trait = "0.1.77"
tokio = { version = "1.36.0", features = ["fs", "process", "macros", "rt-multi-thread"] }
wasmtime = "18.0.1"

[workspace]
